export const ProductTitle = [
  {
    name: "Бүтээгдэхүүн",
  },
  {
    name: "Ангилал",
  },
  {
    name: "Үнэ",
  },
  {
    name: "Үлдэгдэл",
  },
  {
    name: "Зарагдсан",
  },
  {
    name: " Нэмсэн огноо",
  },
];
export const Product = [
  {
    id: "1",
    src: "/blackBack.png",
    number: "0001",
    name: "Laptop цүнх",
    type: "Эмэгтэй, цүнх",
    price: "19,000₮",
    piece: "76  ",
    sale: "30",
    date: "2024-01-10",
  },
  {
    id: "2",
    src: "/light.png",
    number: "0002",
    name: "Гэрэл",
    type: "Эмэгтэй, гутал",
    price: "16,600₮",
    piece: "76  ",
    sale: "30",
    date: "2024-01-10",
  },
  {
    id: "3",
    src: "/earRings.png",
    number: "0003",
    name: "Ээмэг",
    type: "Эмэгтэй, цамц",
    price: "6,600₮",
    piece: "76  ",
    sale: "30",
    date: "2024-01-10",
  },
  {
    id: "4",
    src: "/clip.png",
    number: "0004",
    name: "Хавчаар",
    type: "Эмэгтэй, цаг",
    price: "6,000₮",
    piece: "76  ",
    sale: "30",
    date: "2024-01-10",
  },
  {
    id: "5",
    src: "/clip.png",
    number: "0005",
    name: "Хавчаар",
    type: "Эмэгтэй, цаг",
    price: "6,000₮",
    piece: "76  ",
    sale: "30",
    date: "2024-01-10",
  },
  {
    id: "6",
    src: "/clip.png",
    number: "0006",
    name: "Хавчаар",
    type: "Эмэгтэй, цаг",
    price: "6,000₮",
    piece: "76  ",
    sale: "30",
    date: "2024-01-10",
  },
  {
    id: "7",
    src: "/clip.png",
    number: "0007",
    name: "Хавчаар",
    type: "Эмэгтэй, цаг",
    price: "6,000₮",
    piece: "76  ",
    sale: "30",
    date: "2024-01-10",
  },
  {
    id: "8",
    src: "/clip.png",
    number: "0008",
    name: "Хавчаар",
    type: "Эмэгтэй, цаг",
    price: "6,000₮",
    piece: "76  ",
    sale: "30",
    date: "2024-01-10",
  },
  {
    id: "9",
    src: "/clip.png",
    number: "0009",
    name: "Хавчаар",
    type: "Эмэгтэй, цаг",
    price: "6,000₮",
    piece: "76  ",
    sale: "30",
    date: "2024-01-10",
  },
];
